## Video 1.1.1

In [ ]:
import numpy as np

#### Numeric data, multiple formats

In [ ]:
# 1-dimensonal array, a vector
A1 = np.array([1, 2, 3, 4, 5])

# 2-dimensional array, a matrix
A2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, a tensor
A3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

#### Easy to query data properties in Numpy

In [ ]:
print(A1.shape)
print(A1)
print(A1.dtype)

In [ ]:
print(A2.shape)
print(A2)
print(A2.dtype)

In [ ]:
print("This is A3 : \n", A3)
print("Shape of A3 : ",A3.shape)
print("Size of A3 : ",A3.size)
print("Dimension of A3 : ",A3.ndim)

#### Access an element 

In [ ]:
# For a 1D array (vector)
print("Second element of A1:", A1[1])

# For a 2D array (matrix)
print("Element at row 1, column 2 of A2:", A2[1, 2])

# For a 3D array
print("Element at matrix 0, row 2, column 1 of A3:", A3[0, 2, 1])

#### Access a range of elements 

In [ ]:
#A1 = np.array([1, 2, 3, 4, 5])
print(A1[1:3])


In [ ]:
print(A1[1:4][::-1])   ## Access and flip the order

In [ ]:
A1 > 3    ##Check per element

In [ ]:
#A2 = np.array([[1, 2.0, 3.3],
#              [4, 5, 6.5]])

print( A2[:,1])

In [ ]:
print( A3[0, 0:2, 0:2])

#### Generate with Numpy

In [ ]:
X = np.arange(5)
print(X)

In [ ]:
X = np.arange(0,10,2)
print(X)

In [ ]:
O = np.ones((3))  
Z = np.zeros((3,3))
R = np.random.rand(3,3,3)   # can also generate Normal dist.

O,Z,R

#### Arithmetic Operations

In [ ]:
print("A1 =", A1)
print("A1 + 5 =", A1 + 5)
print("A1 * 2 =", A1 * 2)

#### Matrix multiplication

In [ ]:
#A[i,j] = A[i,j] × B[i,j]

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B
print(C)

In [ ]:
#linear algebra matrix multiplication  (Dot product)
C= A @ B
print(C)

#### Exercise: Create a 10 by 10 "Box" pattern 

[[1 1 1 1 1 1 1 1 1 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 0 0 0 0 0 0 0 0 1]<br>
 [1 1 1 1 1 1 1 1 1 1]]

## Video 1.1.2

#### Solution: Create a 10 by 10 "Box" pattern 


In [ ]:
box = np.ones((10, 10), dtype=int)
box[1:-1, 1:-1] = 0
print(box)

In [ ]:
box = np.pad(np.zeros((8, 8), dtype=int), 1, constant_values=1)
print(box)

In [ ]:
box = np.ones((10, 10), dtype=int)

#### How fast in Numpy?

In [ ]:
import numpy as np
import time

N = 10_000_000
data_list = list(range(N))
data_np = np.arange(N)

#### Run native python

In [ ]:
def python_sum(lst):
    total = 0
    for x in lst:
        total += x
    return total


In [ ]:
start = time.perf_counter()
py_result = python_sum(data_list)
py_time = time.perf_counter() - start

#### use Numpy

In [ ]:
start = time.perf_counter()
np_result = np.sum(data_np)
np_time = time.perf_counter() - start


In [ ]:
print(f"Pure Python sum: {py_time:.4f} s")
print(f"NumPy sum:       {np_time:.6f} s")
print(f"NumPy speedup:   {py_time/np_time:.1f}x faster")


## Video 1.1.3

#### Add dimensions to an array

In [ ]:
m = np.arange(6).reshape((2,3))
print(m)

In [ ]:
print( m[np.newaxis,:,:])
print(" ")
print( m[np.newaxis,:,:].shape)

In [ ]:
print( m[:,:,np.newaxis] )
print(" ")
print( m[:,:,np.newaxis].shape )

#### Reshape an array

In [ ]:
m = np.arange(6).reshape((2,3))
print(m)

In [ ]:
m.transpose()

In [ ]:
m.reshape((3,2))

#### An image is an array

In [ ]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

# Load the image into a NumPy array
photo = mpimg.imread("horses.jpeg")   

# Inspect its structure
print("Shape:", photo.shape)   # (height, width, channels)
print("Dtype:", photo.dtype)   # usually uint8, values 0-255
print("Type:", type(photo))    # numpy.ndarray

# Display it
plt.imshow(photo)
plt.axis("off")


In [ ]:
SEPIA = np.array([[0.393, 0.769, 0.189],
                   [0.349, 0.686, 0.168],
                   [0.272, 0.534, 0.131]], dtype=np.float32)

In [ ]:
SEPIA.shape

In [ ]:
photo[:,:,:,np.newaxis].shape

In [ ]:
new_image = SEPIA.reshape((1,1,3,3)) @ photo[:,:,:,np.newaxis] /255
plt.imshow(new_image[:,:,:,0].clip(0,1))

1. Define a new 3x3 matrix to multiply by the image to generate the original image

2. Define a new matrix to multiply by the image to generate a gray-scale image (asume average of R,G,B)

3. Flip the image sideways, and up-side downn

4. Change the order of the horses

5. transpose the image

## solutions..

1. Define new matrix to multiply by the image to generate the origical image

In [ ]:
no_color_change = np.eye(3)
no_color_change

In [ ]:
new=no_color_change.reshape((1,1,3,3))@ photo[:,:,:,np.newaxis]/255
plt.imshow(new[:,:,:,0].clip(0,1))

2. Define new matrix to multiply by the image to generate a gray-scale image

In [ ]:
Average = np.array([[0.333, 0.333, 0.333],
                   [0.333, 0.333, 0.333],
                   [0.333, 0.333, 0.333]], dtype=np.float32)

In [ ]:
new=Average.reshape((1,1,3,3))@ photo[:,:,:,np.newaxis]/255
plt.imshow(new[:,:,:,0].clip(0,1))

In [ ]:
plt.imshow(photo[:,:,:].mean(axis=2), cmap="gray")

3. Flip the image sideways

In [ ]:
plt.imshow(photo[:,::-1,:])

In [ ]:
plt.imshow(photo[::-1,:,:])   ## And upside downs


4. Change the order of the horses

In [ ]:
left_horse=photo[:,0:910,:] 
right_horse=photo[:,1600:2500,:]
mid_horse=photo[:,911:1599,:]

plt.imshow(np.hstack([mid_horse, left_horse, right_horse]))

5. transpose the image

In [ ]:
plt.imshow(photo.transpose((1,0,2)))

Look at what happen when you reshape instead of transpose

In [ ]:
plt.imshow(photo.reshape((2500,1657, 3)))