In [1]:
import numpy as np
import pandas as pd
from utils import validate_sales_results, validate_titanic_stats

In [2]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
print(a1.shape)
print(a1)

(3,)
[1 2 3]


In [4]:
print(a2.shape)
print(a2)

(2, 3)
[[1.  2.  3.3]
 [4.  5.  6.5]]


In [5]:
print(a3.shape)
print(a3)

(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [6]:
# Accessing elements in arrays
# We use 0-based indexing
# For a 1D array (vector)
print("Second element of a1:", a1[1])

# For a 2D array (matrix)
print("Element at row 1, column 2 of a2:", a2[1, 2])

# For a 3D array
print("Element at matrix 0, row 2, column 1 of a3:", a3[0, 2, 1])

Second element of a1: 2
Element at row 1, column 2 of a2: 6.5
Element at matrix 0, row 2, column 1 of a3: 8


In [7]:
### Arithmetic Operations
# You can perform standard arithmetic operations directly on NumPy arrays.
# Basic operators: +, -, *, /, //, **, %
# Other arithmetic functions include: np.exp(), np.log(), np.dot(), and broadcasting.

print("a1 + 5 =", a1 + 5)
print("a2 * 2 =", a2 * 2)
print("a1 - 1 =", a1 - 1)



a1 + 5 = [6 7 8]
a2 * 2 = [[ 2.   4.   6.6]
 [ 8.  10.  13. ]]
a1 - 1 = [0 1 2]


In [8]:
### Aggregation
# Aggregation involves combining the values in an array to get a single summary value.
# Other aggregation functions include: np.std(), np.var(), np.min(), np.argmin(), np.argmax().
# You can also use the axis parameter to perform aggregations along a specific dimension (e.g., a2.min(axis=0)).

print("Sum of a1:", np.sum(a1))
print("Mean of a2:", np.mean(a2))
print("Max of a2:", np.max(a2))


Sum of a1: 6
Mean of a2: 3.6333333333333333
Max of a2: 6.5


### Exercise: Sales Calculation

1.  Create a NumPy array named `prices` representing the price of three different items: `[10, 15, 20]`.
2.  Create another NumPy array named `quantity_sold` representing how many of each item was sold: `[5, 8, 3]`.
3.  Calculate the total revenue for *each* item (price * quantity).
4.  Calculate the total revenue for *all* items combined.
5.  Pass your results from steps 3 and 4 to the `validate_sales_results` function to check your work.


In [ ]:
prices = np.array([10, 15, 20])
quantity_sold = np.array([5, 8, 3])

# 3. Calculate revenue for each item
# item_revenues = ...

# 4. Calculate total revenue
# total_revenue = ...

# 5. Validate the results
# validate_sales_results(item_revenues, total_revenue)

TypeError: unsupported operand type(s) for -: 'ellipsis' and 'float'

In [ ]:
import pandas as pd

# Increase the maximum width of the display in characters
pd.set_option('display.width', 1000)
# (Optional) Ensure it never hides columns if you have a lot of them
pd.set_option('display.max_columns', None)

In [ ]:
# Creating a Pandas Series
passenger_classes = pd.Series(["First", "Second", "Third"])
print(passenger_classes)

You can create a DataFrame from a Python dictionary, where the keys become the column names.

In [ ]:
# Creating a Pandas DataFrame
passenger_data = pd.DataFrame({"Name": ["Braund, Mr. Owen", "Cumings, Mrs. John", "Heikkinen, Miss. Laina"], "Age": [22, 38, 26]})
print(passenger_data)

While you can create data from scratch, you'll usually import it from an external file. The pd.read_csv() function is one of the most common ways to do this.

In [ ]:
# Import data from titanic.csv
titanic_data = pd.read_csv("titanic.csv")
print(titanic_data)

### Describing Data
After loading data, it's important to inspect it. Pandas provides several functions to quickly get an overview of your DataFrame.

• ```.dtypes``` shows the data type of each column.
• ```.describe()``` gives a statistical summary of the numerical columns.
• ```.info()``` provides a concise summary of the DataFrame, including the number of non-null values in each column.

In [ ]:
# Check the data types of each column
print("--- Data Types ---")
print(titanic_data.dtypes)
print("\n")

# Get a statistical summary of the DataFrame
print("--- Statistical Summary ---")
print(titanic_data.describe())
print("\n")

# Get more information about the DataFrame
print("--- DataFrame Info ---")
titanic_data.info()

### Viewing and Selecting Data
Some common methods for viewing and selecting data in a pandas DataFrame include:

* `DataFrame.head(n)` - Displays the first n rows.
* `DataFrame.tail(n)` - Displays the last n rows.
* `DataFrame.loc[]` - Accesses a group of rows and columns by labels.
* `DataFrame.iloc[]` - Accesses a group of rows and columns by integer indices.

In [ ]:
# Show the first 5 rows
titanic_data.head()

In [ ]:
# Select row at index 3
titanic_data.loc[3]

### Filtering and Finding Outliers
Sometimes you want to find specific rows that match a condition, such as outliers. You can do this using **Boolean Indexing** (Filtering).

For example, let's find the passengers who paid an extremely high fare (over $300).

In [ ]:
# Find the outliers who paid a massive fare!
expensive_tickets = titanic_data[titanic_data['Fare'] > 300]
print("Passengers who paid over $300:")
print(expensive_tickets)

### Exercise: Titanic Statistics

1. Load the `titanic.csv` file into a DataFrame called `my_titanic_data`.
2. Calculate the average passenger age and save it to `average_age`.
3. Calculate the maximum fare paid and save it to `max_fare`.
4. Calculate the total number of survivors and save it to `total_survivors`.
5. Find the total number of passengers older than 60 and save it to `senior_citizens`.
6. Call `validate_titanic_stats(average_age, max_fare, total_survivors, senior_citizens)` to check your answers!

In [ ]:
import pandas as pd
from utils import validate_titanic_stats

# 1. Load the titanic.csv data
my_titanic_data = ...

# 2. Calculate average age
average_age = ...

# 3. Calculate max fare
max_fare = ...

# 4. Calculate total survivors
total_survivors = ...

# 5. Find the total number of passengers older than 60
senior_citizens = ...

# 6. Validate your results
validate_titanic_stats(average_age, max_fare, total_survivors, senior_citizens)

## Introduction to Matplotlib
Matplotlib is a visualization library for Python. If you want to display something in a chart or graph, matplotlib can help you do that programmatically.

Let's start by importing `pyplot`, a submodule for creating interactive plots.

In [ ]:
import matplotlib.pyplot as plt

### Creating a Simple Plot
The `plt.plot()` function is recommended for simple plots. Let's plot some X and Y coordinates.

In [ ]:
x = [1, 2, 3, 4]
y = [11, 22, 33, 44]

plt.plot(x, y);

### Customizing Your Plot
You can easily add titles and labels to your plot using `plt.title()`, `plt.xlabel()`, and `plt.ylabel()`.

In [ ]:
plt.plot(x, y)
plt.title("My First Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis");

### The Object-Oriented (OO) API
While `plt.plot()` is great for quick plots, the **Object-Oriented (OO) API** is recommended for more complex plots. 
We create a `Figure` (the blank canvas) and an `Axes` (the actual plot) using `plt.subplots()`.

In [ ]:
# Create a figure and an axes
fig, ax = plt.subplots(figsize=(6, 4))

# Plot data on the axes
ax.plot(x, y)
ax.set_title("OO API Plot")
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis");

### Scatter Plots and Histograms
Using the OO API, we can easily change the type of plot. 
- **Scatter plots** are great for seeing the relationship between two variables.
- **Histograms** are great for seeing the distribution of a single variable.

In [ ]:
fig, ax = plt.subplots(figsize=(5, 3))
ax.scatter(x, y)
ax.set_title("A Simple Scatter Plot");

In [ ]:
fig, ax = plt.subplots(figsize=(5, 3))
ax.hist(y)
ax.set_title("A Simple Histogram");

### Plotting directly from Pandas
Because Pandas is tightly integrated with Matplotlib, you can actually plot data directly from your DataFrames! Let's plot the distribution of Fares from the Titanic dataset.

In [ ]:
# Make sure we have our data loaded
import pandas as pd
titanic_data = pd.read_csv("titanic.csv")

# Plot a histogram of the Fare column directly from Pandas
titanic_data['Fare'].plot.hist(bins=20)
plt.title("Distribution of Titanic Fares");

### Exercise: Visualizing the Titanic

1. Create a figure and axes using `plt.subplots()`.
2. Create a scatter plot on your axes with `titanic_data['Age']` on the x-axis and `titanic_data['Fare']` on the y-axis.
3. Add a title, an x-axis label, and a y-axis label to your plot.
4. In the next cell, use Pandas to directly plot a histogram of `titanic_data['Age']`.

In [ ]:
# 1. Create figure and axes
fig, ax = ...

# 2. Create a scatter plot of Age vs Fare
...

# 3. Add title and labels
...

In [ ]:
# 4. Plot a histogram of the Age column directly from Pandas
...